# Generated by Django 5.1.3 on 2024-11-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.RemoveField(
            model_name="networknode",
            name="level",
        ),
        migrations.AlterField(
            model_name="networknode",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="house_number",
            field=models.CharField(max_length=50, verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="network.networknode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="network_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="network.networknode",
                verbose_name="Звено сети",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(verbose_name="Дата выхода продукта на рынок"),
        ),
    ]
